Repository instana/go-sensor, pull requests merged in 2023-09, with the labels that each got.

#449 Marshal map issue
  example/http-database-greeter/go.mod
  json_span.go
  tracer.go
  util.go
Labels: bug, ready for review

#452 Instrumentation support for AWS SDK v2
  .circleci/config.yml
  instrumentation/instaawsv2/LICENSE.md
  instrumentation/instaawsv2/Makefile
  instrumentation/instaawsv2/README.md
  instrumentation/instaawsv2/aws.go
  instrumentation/instaawsv2/aws_test.go
  instrumentation/instaawsv2/dynamodb.go
  instrumentation/instaawsv2/dynamodb_test.go
  instrumentation/instaawsv2/example_lambda_test.go
  instrumentation/instaawsv2/example_s3_test.go
  instrumentation/instaawsv2/example_sns_test.go
  instrumentation/instaawsv2/example_sqs_test.go
  instrumentation/instaawsv2/go.mod
  instrumentation/instaawsv2/go.sum
  instrumentation/instaawsv2/lambda.go
  instrumentation/instaawsv2/lambda_test.go
  instrumentation/instaawsv2/propagation.go
  instrumentation/instaawsv2/propagation_test.go
  instrumentation/instaawsv2/s3.go
  instrumentation/instaawsv2/s3_test.go
  instrumentation/instaawsv2/sns.go
  instrumentation/instaawsv2/sns_test.go
  instrumentation/instaawsv2/sqs.go
  instrumentation/instaawsv2/sqs_test.go
  instrumentation/instaawsv2/strings_test.go
  instrumentation/instaawsv2/tags.go
Labels: feature, ready for review

#457 Instana instrumentation of aws-sdk-go-v2
  instrumentation/instaawsv2/version.go
Labels: ready for review

#446 SQL Driver instrumentation: Database auto detection
  .circleci/config.yml
  docker-compose.yaml
  example/http-database-greeter/main.go
  example/sql-mysql/go.mod
  example/sql-mysql/go.sum
  example/sql-mysql/main.go
  example/sql-redis/go.mod
  example/sql-redis/go.sum
  example/sql-redis/main.go
  instrumentation_sql.go
  instrumentation_sql_go1.10.go
  instrumentation_sql_stmt.go
  instrumentation_sql_test.go
  registered_span.go
  sql_conn_prepare_context.go
  sql_execer.go
  sql_execer_context.go
  sql_queryer.go
  sql_queryer_context.go
  sql_stmt_execer_context.go
  sql_stmt_queryer_context.go
Labels: enhancement, ready for review
