Repository instana/go-sensor, pull requests merged in 2024-09, with the labels that each got.

#893 feat: added generic serverless agent
  Makefile
  README.md
  docs/generic_serverless_agent.md
  generic_serverless_agent.go
  generic_serverless_agent_test.go
  go.mod
  go.sum
  sensor.go
Labels: tekton_ci

#896 Updated dependencies of example programs
  example/beego/go.mod
  example/beego/go.sum
  example/cosmos/go.mod
  example/couchbase/go.mod
  example/couchbase/go.sum
  example/gin/go.mod
  example/gin/go.sum
  example/gorm-postgres/go.mod
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.mod
  example/gorm-sqlite/go.sum
  example/graphql/go.mod
  example/graphql/go.sum
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/http-database-greeter/go.mod
  example/http-database-greeter/go.sum
  example/httprouter/go.mod
  example/httprouter/go.sum
  example/kafka-producer-consumer/go.mod
  example/kafka-producer-consumer/go.sum
  example/opentracing/go.mod
  example/opentracing/go.sum
  example/pgxv5/go.mod
  example/pgxv5/go.sum
  example/sarama/go.mod
  example/sarama/go.sum
  example/sql-mysql-gin/go.mod
  example/sql-mysql-gin/go.sum
  example/sql-mysql/go.mod
  example/sql-mysql/go.sum
  example/sql-opendb/go.mod
  example/sql-opendb/go.sum
  example/sql-redis/go.mod
  example/sql-redis/go.sum
Labels: ready for review, tekton_ci

#897 Removing toolchain from go.mod file
  instrumentation/instacosmos/go.mod
Labels: ready for review, tekton_ci

#882 feat: support parallel processing for couchbase integration test
  .tekton/ci-build/pipeline.yaml
  .tekton/ci-build/task.yaml
  docker-compose-integration.yaml
  docker-compose.yaml
  instrumentation/instagocb/bucket_manager_test.go
  instrumentation/instagocb/cluster.go
  instrumentation/instagocb/cluster_test.go
  instrumentation/instagocb/collection_ds_list_test.go
  instrumentation/instagocb/collection_ds_map_test.go
  instrumentation/instagocb/collection_ds_queue_test.go
  instrumentation/instagocb/collection_ds_set_test.go
  instrumentation/instagocb/collection_manager_test.go
  instrumentation/instagocb/collection_test.go
  instrumentation/instagocb/instagocb_test.go
  instrumentation/instagocb/scope_test.go
  instrumentation/instagocb/transactions_test.go
Labels: enhancement, tekton_ci

#908 refactor: removed Close method in couchbase as the interface is satisfied by embedded struct
  instrumentation/instagocb/cluster.go
Labels: tekton_ci

#905 chore: added a CHANGELOG.md for tracking the releases of go-sensor core SDK
  CHANGELOG.md
Labels: ready for review, tekton_ci

#904 chore: added new columns in the tracer reports
  .tekton/tracer-reports/task.yaml
  currency_report.sh
Labels: tekton_ci

#913 chore: fixed currency script with an issue in some packages when fetching the immediate next version
  currency_report.sh
Labels: tekton_ci

#914 refactor: refactored instagocb unit test to fix random failures
  instrumentation/instagocb/collection_test.go
  instrumentation/instagocb/instagocb_test.go
  instrumentation/instagocb/transactions_test.go
Labels: tekton_ci

#919 chore: fixed the automation script to skip PR creation if a PR alredy exists for the instrumentation package
  version_updater.sh
Labels: tekton_ci

#922 chore: fixed some minor issues in the currency automation scripts
  .tekton/tracer-reports/task.yaml
  currency_report.sh
  version_updater.sh
Labels: tekton_ci
