Repository instana/go-sensor, pull requests merged in 2024-02, with the labels that each got.

#605 Increasing waiting time in GraphQL unit tests
  instrumentation/instagraphql/instagraphql_test.go
Labels: ready for review, experiment

#612 Update slack_notification.yml to include release-notes to slack
  .github/workflows/slack_notification.yml
Labels: ready for review

#607 refactor: refactored example programs to a common location
  .circleci/config.yml
  example/README.md
  example/beego/go.mod
  example/beego/go.sum
  example/gin/go.mod
  example/gin/go.sum
  example/gorm-postgres/go.mod
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.mod
  example/gorm-sqlite/go.sum
  example/graphql/data.json
  example/graphql/database.go
  example/graphql/go.mod
  example/graphql/go.sum
  example/graphql/main.go
  example/graphql/model.go
  example/graphql/pubsub.go
  example/graphql/schema.go
  example/graphql/ws.go
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/http-database-greeter/go.mod
  example/http-database-greeter/go.sum
  example/httprouter/go.mod
  example/httprouter/go.sum
  example/kafka-producer-consumer/go.mod
  example/kafka-producer-consumer/go.sum
  example/opentracing/go.mod
  example/opentracing/go.sum
  example/sarama/README.md
  example/sarama/bin/wait-for-it.sh
  example/sarama/consumer.go
  example/sarama/docker-compose.yml
  example/sarama/go.mod
  example/sarama/go.sum
  example/sarama/main.go
  example/sarama/producer.go
  example/sql-mysql/go.mod
  example/sql-redis/go.mod
  instrumentation/instagraphql/README.md
  instrumentation/instagraphql/example/go.mod
Labels: ready for review

#515 Cosmos instrumentation
  .circleci/config.yml
  .github/workflows/coverage_run_and_upload.yml
  Makefile
  example/cosmos/README.md
  example/cosmos/go.mod
  example/cosmos/go.sum
  example/cosmos/main.go
  instrumentation/instacosmos/LICENSE.md
  instrumentation/instacosmos/Makefile
  instrumentation/instacosmos/README.md
  instrumentation/instacosmos/client.go
  instrumentation/instacosmos/client_test.go
  instrumentation/instacosmos/container_client.go
  instrumentation/instacosmos/container_client_test.go
  instrumentation/instacosmos/example_test.go
  instrumentation/instacosmos/go.mod
  instrumentation/instacosmos/go.sum
  instrumentation/instacosmos/instacosmos.go
  instrumentation/instacosmos/partition_key.go
  instrumentation/instacosmos/partition_key_test.go
  instrumentation/instacosmos/version.go
  instrumentation_sql.go
  registered_span.go
  supported_versions.md
Labels: enhancement, do not merge, feature, ready for review
