Repository instana/go-sensor, pull requests merged in 2024-11, with the labels that each got.

#946 chore: updated the examples code with the latest packages
  example/beego/go.sum
  example/cosmos/go.sum
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.sum
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/pgxv5/go.sum
Labels: ready for review, tekton_ci

#947 chore: updated golang version policy in tekton tasks
  .tekton/ci-build/task.yaml
  .tekton/tracer-reports/task.yaml
Labels: tekton_ci

#949 chore: minor modification to the currency script to correctly update the 'Note' column when all versions are up-to-date
  currency_report.sh
Labels: tekton_ci

#951 chore: updated the go.mod files of examples
  example/cosmos/go.mod
  example/cosmos/go.sum
  example/grpc-client-server/go.mod
Labels: ready for review, tekton_ci

#938 poc: refactoring sql instrumentation
  instrumentation_sql.go
  instrumentation_sql_stmt.go
  instrumentation_sql_test.go
  sql_data.go
  sql_execer.go
  sql_execer_context.go
  sql_queryer.go
  sql_queryer_context.go
  sql_stmt_execer_context.go
  sql_stmt_queryer_context.go
  sql_test.go
  sql_wrappers.go
  tags.go
Labels: tekton_ci, poc

#956 chore(examples): updated the packages in example programs
  example/beego/go.mod
  example/beego/go.sum
Labels: ready for review, tekton_ci
