Repository instana/go-sensor, pull requests merged in 2024-07, with the labels that each got.

#845 refactor:updated the dependencies for the examples
  example/beego/go.mod
  example/beego/go.sum
  example/couchbase/go.mod
  example/couchbase/go.sum
Labels: ready for review, tekton_ci

#846 refactor:updated the dependencies for grpc example
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
Labels: ready for review, tekton_ci

#850 fix: DB2 spans are tagged as MySQL spans instead of generic DB spans
  docs/sql.md
  instrumentation_sql.go
  instrumentation_sql_test.go
Labels: bug, tekton_ci

#856 chore:updated the dependencies for examples
  example/beego/go.mod
  example/cosmos/go.mod
  example/couchbase/go.mod
  example/couchbase/go.sum
  example/gin/go.mod
  example/gorm-postgres/go.mod
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.mod
  example/gorm-sqlite/go.sum
  example/graphql/go.mod
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/httprouter/go.mod
  example/kafka-producer-consumer/go.mod
  example/pgxv5/go.mod
  example/pgxv5/go.sum
  example/sarama/go.mod
Labels: ready for review, tekton_ci

#861 chore:updated dependencies
  example/gorm-postgres/go.mod
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.mod
  example/gorm-sqlite/go.sum
Labels: ready for review, tekton_ci

#866 chore: corrected package name for instaredis/v2 in the ci/cd markdown file
  supported_versions.md
Labels: tekton_ci

#868 chore:updated dependencies for example
  example/couchbase/go.mod
  example/couchbase/go.sum
Labels: ready for review, tekton_ci
