Repository instana/go-sensor, pull requests merged in 2024-12, with the labels that each got.

#959 chore: sonarcloud pipeline
  .github/workflows/coverage_run_and_upload_sonarcloud.yml
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: tekton_ci

#961 chore: fixed issue with running integration tests in the core package for SonarCloud check
  .github/workflows/coverage_run_and_upload_sonarcloud.yml
  azure_agent_test.go
  azure_container_apps_test.go
  fargate_agent_test.go
  gcr_agent_test.go
  generic_serverless_agent_test.go
  lambda_agent_test.go
Labels: tekton_ci

#962 chore: updated sonarcloud.yml to use GITHUB_TOKEN
  .github/workflows/sonarcloud.yml
Labels: tekton_ci

#964 fix: the test database is not cleaned up from the Cosmos account when integration tests fail
  example/cosmos/README.md
  instrumentation/instacosmos/container_client_test.go
Labels: bug, tekton_ci

#972 fix: redis span finished before the actual redis command was executed
  example/README.md
  example/instaredis-v2-example/go.mod
  example/instaredis-v2-example/go.sum
  example/instaredis-v2-example/main.go
  instrumentation/instaredis/v2/instaredis.go
  instrumentation/instaredis/v2/instaredis_test.go
Labels: tekton_ci

#955 perf: optimize SQL based database instrumentation
  context.go
  context_test.go
  instrumentation_sql.go
  instrumentation_sql_stmt.go
  instrumentation_sql_test.go
  internal/bin/sql/sql_wrappers.tpl
  sql_data.go
  sql_execer.go
  sql_execer_context.go
  sql_queryer.go
  sql_queryer_context.go
  sql_stmt_execer_context.go
  sql_stmt_queryer_context.go
  sql_test.go
  sql_wrappers.go
  tags.go
Labels: enhancement, tekton_ci

#958 feat: instrumentation of fasthttp
  example/README.md
  example/basic_usage_fasthttp/README.md
  example/basic_usage_fasthttp/go.mod
  example/basic_usage_fasthttp/go.sum
  example/basic_usage_fasthttp/main.go
  instrumentation/instafasthttp/LICENSE.md
  instrumentation/instafasthttp/Makefile
  instrumentation/instafasthttp/README.md
  instrumentation/instafasthttp/go.mod
  instrumentation/instafasthttp/go.sum
  instrumentation/instafasthttp/instrumentation.go
  instrumentation/instafasthttp/instrumentation_test.go
  instrumentation/instafasthttp/version.go
Labels: tekton_ci

#974 feat: instrumentation of fasthttp client methods
  example/basic_usage_fasthttp/README.md
  example/basic_usage_fasthttp/go.mod
  example/basic_usage_fasthttp/main.go
  instrumentation/instafasthttp/README.md
  instrumentation/instafasthttp/client.go
  instrumentation/instafasthttp/client_test.go
  instrumentation/instafasthttp/instrumentation_helper.go
  instrumentation/instafasthttp/roundtripper.go
  instrumentation/instafasthttp/rounttripper_test.go
  instrumentation/instafasthttp/server.go
  instrumentation/instafasthttp/server_test.go
Labels: tekton_ci

#984 chore: updated dependencies in the fasthttp example
  example/basic_usage_fasthttp/go.mod
  example/basic_usage_fasthttp/go.sum
Labels: tekton_ci

#987 fix: updated the instafasthttp README documentation with information on supported methods
  instrumentation/instafasthttp/README.md
Labels: tekton_ci

#989 test: added checks to debug the unit test failures in delayed spans
  delayed_spans_test.go
Labels: tekton_ci
