Repository instana/go-sensor, pull requests merged in 2024-04, with the labels that each got.

#701 ci: updated the minimum version of go to 1.21 in tekton
  .tekton/github-eventlistener.yaml
  .tekton/pipeline.yaml
Labels: ready for review, tekton_ci

#705 Correction to Go Tracer version details
  README.md
Labels: ready for review, tekton_ci

#707 Fixed cosmos instrumentation code break if invalid credentials are given
  example/cosmos/go.mod
  example/cosmos/main.go
  instrumentation/instacosmos/README.md
  instrumentation/instacosmos/container_client.go
  instrumentation/instacosmos/example_test.go
Labels: bug, tekton_ci

#740 Updates for examples
  example/beego/go.mod
  example/beego/go.sum
  example/gin/go.sum
  example/gorm-postgres/go.mod
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.mod
  example/gorm-sqlite/go.sum
  example/graphql/go.mod
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/httprouter/go.mod
  example/kafka-producer-consumer/go.sum
  example/sarama/go.sum
Labels: ready for review, tekton_ci

#743 Improvements in the currency automation script
  supported_versions.md
  version_updater.sh
Labels: tekton_ci

#746 Improvements in the currency automation script
  version_updater.sh
Labels: tekton_ci
