Repository instana/go-sensor, pull requests merged in 2025-04, with the labels that each got.

#1080 chore: updated the dependencies of examples
  example/beego/go.sum
  example/cosmos/go.mod
  example/cosmos/go.sum
  example/couchbase/go.mod
  example/couchbase/go.sum
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/pgxv5/go.mod
  example/pgxv5/go.sum
Labels: ready for review, tekton_ci

#1083 fix: refactoring the code for mongodb v2 instrumentation
  instrumentation/instacosmos/go.mod
  instrumentation/instamongo/v2/instamongo.go
Labels: ready for review

#1077 feat: mongo driver v2 instrumentation
  example/README.md
  example/mongo-driver-v2/README.md
  example/mongo-driver-v2/docker-compose.yml
  example/mongo-driver-v2/go.mod
  example/mongo-driver-v2/go.sum
  example/mongo-driver-v2/main.go
  instrumentation/instacosmos/go.mod
  instrumentation/instamongo/v2/LICENSE.md
  instrumentation/instamongo/v2/Makefile
  instrumentation/instamongo/v2/README.md
  instrumentation/instamongo/v2/example_test.go
  instrumentation/instamongo/v2/go.mod
  instrumentation/instamongo/v2/go.sum
  instrumentation/instamongo/v2/instamongo.go
  instrumentation/instamongo/v2/instamongo_test.go
  instrumentation/instamongo/v2/span_cache.go
  instrumentation/instamongo/v2/version.go
Labels: tekton_ci

#1090 chore: updated the dependencies of examples
  example/basic_usage/go.mod
  example/basic_usage/go.sum
  example/basic_usage_fasthttp/go.mod
  example/basic_usage_fasthttp/go.sum
  example/beego/go.mod
  example/beego/go.sum
  example/cosmos/go.mod
  example/couchbase/go.mod
  example/gin/go.mod
  example/gorm-postgres/go.mod
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.mod
  example/gorm-sqlite/go.sum
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/grpc/go.mod
  example/grpc/go.sum
  example/http-database-greeter/go.mod
  example/httprouter/go.mod
  example/instaredis-v2-example/go.mod
  example/kafka-producer-consumer/go.mod
  example/mongo-driver-v2/go.mod
  example/opentracing/go.mod
  example/pgxv5/go.mod
  example/sarama/go.mod
  example/sql-mysql-gin/go.mod
  example/sql-mysql-gin/go.sum
  example/sql-mysql/go.mod
  example/sql-opendb/go.mod
  example/sql-redis/go.mod
  instrumentation/instagocb/go.mod
Labels: ready for review, tekton_ci

#1110 fix: fixed tracer config precedence to the correct order
  agent_test.go
  fsm.go
  fsm_test.go
  options.go
  options_test.go
  tracer_options.go
Labels: tekton_ci
