Repository instana/go-sensor, pull requests merged in 2025-01, with the labels that each got.

#995 fix: addressed an issue where connection strings for databases such as PostgreSQL were wrongly identified as Redis connections
  instrumentation_sql.go
  instrumentation_sql_test.go
Labels: bug, tekton_ci

#998 fix: the problem of missing spans while using the Row function in GORM has been resolved
  instrumentation/instagorm/instagorm.go
  instrumentation/instagorm/instagorm_test.go
Labels: bug, tekton_ci

#1003 chore: sonar jobs cleanup - removed obsolete jobs and streamlined the Sonar Cloud job for both pull requests and branch analysis
  .github/workflows/coverage_run_and_upload.yml
  .github/workflows/coverage_run_and_upload_sonarcloud.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarcloud_for_pr.yml
  .github/workflows/sonarqube.yml
Labels: enhancement, tekton_ci

#1013 chore: currency update for the google cloud storage v1.50.0
  instrumentation/cloud.google.com/go/go.mod
  instrumentation/cloud.google.com/go/go.sum
  instrumentation/cloud.google.com/go/iam/doc.go
  instrumentation/cloud.google.com/go/iam/iam.go
  instrumentation/cloud.google.com/go/internal/tags/tags.go
  instrumentation/cloud.google.com/go/internal/trace.go
  instrumentation/cloud.google.com/go/pubsub/example_test.go
  instrumentation/cloud.google.com/go/pubsub/pubsub.go
  instrumentation/cloud.google.com/go/pubsub/pubsub_test.go
  instrumentation/cloud.google.com/go/pubsub/push.go
  instrumentation/cloud.google.com/go/pubsub/push_test.go
  instrumentation/cloud.google.com/go/pubsub/subscription.go
  instrumentation/cloud.google.com/go/pubsub/subscription_test.go
  instrumentation/cloud.google.com/go/pubsub/topic.go
  instrumentation/cloud.google.com/go/pubsub/topic_test.go
  instrumentation/cloud.google.com/go/storage/acl.go
  instrumentation/cloud.google.com/go/storage/bucket.go
  instrumentation/cloud.google.com/go/storage/copy.go
  instrumentation/cloud.google.com/go/storage/doc.go
  instrumentation/cloud.google.com/go/storage/hmac.go
  instrumentation/cloud.google.com/go/storage/iam.go
  instrumentation/cloud.google.com/go/storage/reader.go
  instrumentation/cloud.google.com/go/storage/storage.go
  instrumentation/cloud.google.com/go/storage/writer.go
  supported_versions.md
Labels: tekton_ci, currency

#1015 chore: updated the packages of example programs
  example/basic_usage_fasthttp/go.mod
  example/basic_usage_fasthttp/go.sum
  example/beego/go.mod
  example/beego/go.sum
  example/cosmos/go.mod
  example/cosmos/go.sum
  example/couchbase/go.mod
  example/couchbase/go.sum
  example/gin/go.mod
  example/gin/go.sum
  example/gorm-postgres/go.mod
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.mod
  example/gorm-sqlite/go.sum
  example/graphql/go.mod
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/httprouter/go.mod
  example/instaredis-v2-example/go.mod
  example/kafka-producer-consumer/go.mod
  example/kafka-producer-consumer/go.sum
  example/pgxv5/go.mod
  example/pgxv5/go.sum
  example/sarama/go.mod
  example/sarama/go.sum
Labels: enhancement, ready for review, tekton_ci

#1020 doc: updated the support documentation
  README.md
Labels: ready for review, tekton_ci

#1012 fix: unit test failures while using instana.InitCollector() API
  collector.go
  collector_test.go
  instrumentation_http_test.go
  sensor.go
Labels: bug, tekton_ci

#1023 rfactor: update Go Tracer unit tests with InitCollector API
  adapters_test.go
  azure_agent_test.go
  azure_container_apps_test.go
  context_test.go
  delayed_spans_test.go
  fargate_agent_test.go
  fsm_test.go
  gcr_agent_test.go
  generic_serverless_agent_test.go
  instrumentation_http_test.go
  instrumentation_sql_go1.10_test.go
  instrumentation_sql_test.go
  json_span_test.go
  lambda_agent_test.go
  propagation_test.go
  recorder_test.go
  registered_span_test.go
  span_context_test.go
  span_test.go
  sql_test.go
Labels: tekton_ci

#1024 fix: added fix for the delayed span testcase failures
  delayed_spans_test.go
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
Labels: bug, ready for review, tekton_ci

#1027 chore: updated the container registry for pulling currency update Tekton job images
  .tekton/tracer-reports/task.yaml
Labels: tekton_ci

#1028 chore: updated the dependencies for examples
  example/basic_usage_fasthttp/go.mod
  example/beego/go.mod
  example/cosmos/go.mod
  example/couchbase/go.mod
  example/couchbase/go.sum
  example/gin/go.mod
  example/gorm-postgres/go.mod
  example/gorm-postgres/go.sum
  example/gorm-sqlite/go.mod
  example/gorm-sqlite/go.sum
  example/graphql/go.mod
  example/grpc-client-server/go.mod
  example/grpc-client-server/go.sum
  example/httprouter/go.mod
  example/instaredis-v2-example/go.mod
  example/kafka-producer-consumer/go.mod
  example/pgxv5/go.mod
  example/pgxv5/go.sum
  example/sarama/go.mod
Labels: ready for review, tekton_ci
